env = Environment(LIBS=['SDLmain', 'SDL2', 'dl', 'GL'],
                  LIBPATH = ['/usr/lib/x86_64-linux-gnu'],
                  CPPPATH=['/usr/include/SDL2'])

cenv = env.Clone(CPPFLAGS = ['--std=c++1y'])


objects = [cenv.Object("%s.cpp" % x) for x in ['game','field','imgui_demo','imgui_draw','imgui','imgui_impl_sdl', 'types', 'main' ] ]
gl3w = env.Object('GL/gl3w.c')

main = env.Program('main' , objects + [gl3w])





